version: "3.9"

services:
  postgres_db:
    container_name: postgresdb
    image: postgres:13

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "dvdrental"

    ports:
      - "5432:5432"

  postgres_seed:
      container_name: postgresseed
      image: postgres:13
      privileged: true
      environment:
          POSTGRES_HOST_AUTH_METHOD: "trust"
          PGPASSWORD: "1234"
      volumes:
          - ./postgres/dvdrental.tar:/tmp/dvdrental.tar:ro
      entrypoint: [ "bash", "-c", "sleep 10 && pg_restore -h postgresdb -U postgres -d dvdrental /tmp/dvdrental.tar" ]
      restart: "no"
      depends_on:
        - "postgres_db"

  pythonExtractor:
    container_name: postgres_json_extractor
    build: ./python/.
    image: postgres_json_extractor
    privileged: true
    depends_on:
        postgres_seed:
            condition: service_completed_successfully
        postgres_db: 
            condition: service_started

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "${UI_PORT?}:8080"